stages:
  - test

pytest:
  stage: test
  image: python:3.10
  variables:
    BUILD_WITH_BRUTE_FORCE: "true"
  script:
    - python -m pip install --upgrade pip
    - python -m pip install pytest
    - python -m pip install ortools
    - python -m pip install .
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml